project:
  type: book

book:
  title: "WS 25/26 Numerik 0 Loesungen"
  author: 
    - "Igor Dimitrov"
    - "Malte Herzog"
  date: "10/10/2025"
  chapters:
    - index.qmd
    - ub1/ub1.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



