name: build
on:
  push: 
    branches: [ master ]
    paths:
      - 'src/**'
      - '.github/workflows/build.yml'
  puLL_request:
    branches: [ master ]
    paths:
      - 'src/**'
      - '.github/workflows/build.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y cmake g++ libgmp-dev
      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build -j
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true